### ISSUE TITLE
WELLKNOWN directory doesn't exist, please create /etc/www/dehydrated and set appropriate permissions.

### ISSUE THREAD

**Issue by amelroua** [dehydrated-io/dehydrated#696] opened 2019-12-10 13:45 UTC
I tried to create a let's encrypt certificate in my openwert router using the following tuto http://blog.shahada.abubakar.net/post/getting-free-ssl-certificates-from-letsencrypt-org-on-openwrt-using-dehydrated-
however when I execute the command : ./dehydrated -c
I get this error : ERROR: WELLKNOWN directory doesn't exist, please create /etc/www/dehydrated and set appropriate permissions.
I have already created /etc/www/dehydrated and I can access to it  and permissions are set @ drwxrwxrwx for /etc/www/dehydrated   and -rwxrwxrwx for etc/dehydrated/config.

**Comment by lukas2511** [comment] 2020-04-28 19:26
Can't reproduce this issue and got no similar reports over any available channel, closing for now.

**Closed by lukas2511** 2020-04-28 19:26 UTC
